services:
  - type: web
    name: faktulite-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishDir: frontend/dist
    routes:
      - type: redirect
        source: /*
        destination: /index.html
